/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "authorization.override": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.pin.update": [],
    "admin.dashboard": [],
    "admin.users.index": [],
    "admin.users.store": [],
    "admin.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.reset-password": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.set-pin": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.roles.index": [],
    "admin.roles.store": [],
    "admin.roles.update": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.activity-logs.index": [],
    "admin.products.index": [],
    "admin.products.store": [],
    "admin.products.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.categories.index": [],
    "admin.categories.store": [],
    "admin.categories.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.categories.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.brands.index": [],
    "admin.brands.store": [],
    "admin.brands.update": [
        {
            "name": "brand",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.brands.destroy": [
        {
            "name": "brand",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.units.index": [],
    "admin.units.store": [],
    "admin.units.update": [
        {
            "name": "unit",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.units.destroy": [
        {
            "name": "unit",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.suppliers.index": [],
    "admin.suppliers.store": [],
    "admin.suppliers.update": [
        {
            "name": "supplier",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.suppliers.destroy": [
        {
            "name": "supplier",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.payment-methods.index": [],
    "admin.outlets.index": [],
    "admin.payment-methods.store": [],
    "admin.payment-methods.update": [
        {
            "name": "paymentMethod",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.payment-methods.destroy": [
        {
            "name": "paymentMethod",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.outlets.store": [],
    "admin.outlets.update": [
        {
            "name": "outlet",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.outlets.destroy": [
        {
            "name": "outlet",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.members.index": [],
    "admin.members.store": [],
    "admin.members.update": [
        {
            "name": "member",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.members.destroy": [
        {
            "name": "member",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.members.reset-pin": [
        {
            "name": "member",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.members.reissue-card": [
        {
            "name": "member",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.members.print-cards": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
