/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "authorization.override": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.pin.update": [],
    "admin.dashboard": [],
    "admin.users.index": [],
    "admin.users.store": [],
    "admin.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.reset-password": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.set-pin": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.roles.index": [],
    "admin.roles.store": [],
    "admin.roles.update": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.activity-logs.index": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
